# Generated by Django 5.1.7 on 2025-03-21 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('password', models.TextField(default=None)),
                ('correo', models.TextField(max_length=255)),
                ('telefono', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='tasks.usuario'),
        ),
    ]
